apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --build local
    kompose.image-pull-policy: Never
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --build local
        kompose.image-pull-policy: Never
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - bash
            - -c
            - python manage.py makemigrations && python manage.py migrate && python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000
          image: cancer:latest
          imagePullPolicy: Never
          name: app
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
